// generated by gorts

export type DogBarkArgs = {
  Name: string;
};

export type DogBarkReply = string;

export interface Dog {
  Bark(args: DogBarkArgs): Promise<DogBarkReply>;
}

export type CatBarkArgs = {
  Name: string;
};

export type CatBarkReply = string;

export interface Cat {
  Bark(args: CatBarkArgs): Promise<CatBarkReply>;
}

export type DuckQuackArgs = {
  Name: string;
};

export type DuckQuackReply = string;

export interface Duck {
  Quack(args: DuckQuackArgs): Promise<DuckQuackReply>;
}

export type RPCService = {
	Dog: Dog;
	Cat: Cat;
	Duck: Duck;
}