package gorts

import (
	"fmt"
	"os"
	"reflect"
	"strings"
)

func goTypeToTSType(goType reflect.Type) string {
	switch goType.Kind() {
	case reflect.String:
		return "string"
	case reflect.Int, reflect.Int64, reflect.Int32, reflect.Int16, reflect.Int8:
		return "number"
	case reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Bool:
		return "boolean"
	case reflect.Slice, reflect.Array:
		return fmt.Sprintf("%s[]", goTypeToTSType(goType.Elem()))
	case reflect.Map:
		return fmt.Sprintf("{ [key: %s]: %s }", goTypeToTSType(goType.Key()), goTypeToTSType(goType.Elem()))
	case reflect.Struct:
		fields := []string{}
		for i := 0; i < goType.NumField(); i++ {
			field := goType.Field(i)
			fields = append(fields, fmt.Sprintf("  %s: %s;", field.Name, goTypeToTSType(field.Type)))
		}
		return fmt.Sprintf("{\n%s\n}", strings.Join(fields, "\n"))
	default:
		return "any"
	}
}

func GenerateTSTypes(services []RPCClass) error {
	outputDirectory := "../client/src/gorts/type.ts"

	concatenatedInterface := "export type RPCService = {\n"

	file, err := os.Create(outputDirectory)
	if err != nil {
		return fmt.Errorf("failed to create TypeScript file: %v", err)
	}
	defer file.Close()

	var tsDefinitions []string

	tsDefinitions = append(tsDefinitions, "// auto-generated by gorts")

	for _, service := range services {
		for _, method := range service.Methods {
			argsType := goTypeToTSType(method.ArgsType)
			replyType := goTypeToTSType(method.ReplyType)

			tsDefinitions = append(tsDefinitions, fmt.Sprintf("export type %s%sArgs = %s;", service.Name, method.Name, argsType))
			tsDefinitions = append(tsDefinitions, fmt.Sprintf("export type %s%sReply = %s;", service.Name, method.Name, replyType))
		}

		serviceInterface := fmt.Sprintf("export interface %s {\n", service.Name)
		for _, method := range service.Methods {
			serviceInterface += fmt.Sprintf("  %s(args: %s%sArgs): Promise<%s%sReply>;\n", method.Name, service.Name, method.Name, service.Name, method.Name)
		}
		serviceInterface += "}"

		tsDefinitions = append(tsDefinitions, serviceInterface)
		concatenatedInterface += fmt.Sprintf("	%s: %s;\n", service.Name, service.Name)
	}

	concatenatedInterface += "}"
	tsDefinitions = append(tsDefinitions, concatenatedInterface)

	_, err = file.WriteString(strings.Join(tsDefinitions, "\n\n"))
	if err != nil {
		return fmt.Errorf("failed to write TypeScript definitions: %v", err)
	}

	fmt.Printf("Generated TypeScript definitions in %s\n", outputDirectory)
	return nil
}
